name: Go fuzz test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  fuzz-lexer-test:
    name: Fuzz escapeValue(...) test
    runs-on: ubuntu-latest
    steps:
        # commit hash == v1.2.0
      - uses: jidicula/go-fuzz-action@4f24eed45b25214f31a9fe035ca68ea2c88c6a13
        with:
          fuzz-time: 30s
          fuzz-regexp: Fuzz_EscapeValue